[project]
name = "recipe-bot"
version = "1.0.0"
description = "Telegram Bot for Recipe API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyrogram>=2.0.106",
    "pytelegrambotapi>=4.27.0",
    "python-dotenv>=1.1.0",
    "tgcrypto>=1.2.5",
]
